parameters:
#    nts_supinfo.example.class: Nts\SupinfoBundle\Example

services:
#    nts_supinfo.example:
#        class: %nts_supinfo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
