<?php

namespace Nts\SupinfoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotationRepository extends EntityRepository
{
}