<?php

namespace Nts\SupinfoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaRepository extends EntityRepository
{
}